name: Main CI

on:
  push:
    tags-ignore:
      - 'v*.*.*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake test
      - name: Build
        run: gem build mapotempo_rubocop.gemspec
        shell: bash
      - name: Post build
        run: ./.github/actions/post-build.sh
        shell: bash
